"""Seed the database with sample questions.

Usage:
    python seed_questions.py

Idempotent: skips questions whose title already exists.
"""

from app import create_app, db
from app.models import Question

app = create_app()

QUESTIONS = [
    # ================================================================
    # 1. 软件测试基础 (7 题)
    # ================================================================
    {
        "question_type": "single",
        "title": "以下哪项是软件测试的主要目的？",
        "option_a": "证明软件没有缺陷",
        "option_b": "发现软件中的缺陷",
        "option_c": "编写更多的代码",
        "option_d": "提高软件的运行速度",
        "correct_answer": "B",
        "explanation": "软件测试的主要目的是发现软件中的缺陷，而不是证明软件没有缺陷。测试只能证明缺陷存在，不能证明缺陷不存在。",
        "difficulty": "easy",
    },
    {
        "question_type": "true_false",
        "title": "穷尽测试（测试所有可能的输入组合）是完全可行的。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "B",
        "explanation": "穷尽测试是不可能的，因为输入组合的数量通常是无限的。测试人员需要使用合理的测试策略来选择最有代表性的测试用例。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "以下哪项不是软件测试的基本原则？",
        "option_a": "测试尽早介入",
        "option_b": "缺陷集群效应",
        "option_c": "测试可以证明软件没有缺陷",
        "option_d": "测试依赖于上下文",
        "correct_answer": "C",
        "explanation": "软件测试的基本原则之一是：测试只能证明缺陷存在，不能证明缺陷不存在。因此「测试可以证明软件没有缺陷」不是测试原则。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "黑盒测试不关注以下哪项？",
        "option_a": "输入数据",
        "option_b": "输出结果",
        "option_c": "程序内部代码逻辑",
        "option_d": "需求规格",
        "correct_answer": "C",
        "explanation": "黑盒测试不关注程序内部结构和代码逻辑，只关注输入和输出，根据需求规格设计测试用例。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "以下哪种测试通常由开发人员完成？",
        "option_a": "系统测试",
        "option_b": "验收测试",
        "option_c": "单元测试",
        "option_d": "回归测试",
        "correct_answer": "C",
        "explanation": "单元测试对软件中最小可测试单元进行验证，通常由开发人员在编码阶段完成。系统测试和验收测试通常由测试团队或用户完成。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "测试和调试的主要区别是什么？",
        "option_a": "没有区别",
        "option_b": "测试是发现缺陷，调试是定位和修复缺陷",
        "option_c": "测试由开发完成，调试由测试完成",
        "option_d": "调试在测试之前进行",
        "correct_answer": "B",
        "explanation": "测试是发现缺陷的过程，调试是定位和修复缺陷的过程。测试人员负责发现缺陷，开发人员负责修复缺陷。",
        "difficulty": "easy",
    },
    {
        "question_type": "true_false",
        "title": "灰盒测试是黑盒测试和白盒测试的结合。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "A",
        "explanation": "灰盒测试结合了黑盒测试和白盒测试的方法，既关注输入输出，也关注部分内部实现。",
        "difficulty": "easy",
    },
    # ================================================================
    # 2. 软件测试流程 STLC (7 题)
    # ================================================================
    {
        "question_type": "single",
        "title": "STLC（软件测试生命周期）的第一个阶段是什么？",
        "option_a": "测试执行",
        "option_b": "测试需求分析",
        "option_c": "测试计划",
        "option_d": "缺陷报告",
        "correct_answer": "B",
        "explanation": "STLC的第一阶段是测试需求分析，明确「测什么」，然后才是测试计划、测试设计、测试执行和测试报告。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "以下哪项不属于测试计划文档的内容？",
        "option_a": "测试范围和目标",
        "option_b": "测试环境",
        "option_c": "具体的测试用例",
        "option_d": "风险评估",
        "correct_answer": "C",
        "explanation": "测试计划描述测试活动的范围、方法、资源和进度安排，具体的测试用例属于测试设计阶段的产出。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "缺陷报告中，「严重程度」通常不包括以下哪个级别？",
        "option_a": "致命",
        "option_b": "严重",
        "option_c": "一般",
        "option_d": "建议",
        "correct_answer": "D",
        "explanation": "缺陷严重程度通常分为致命、严重、一般、轻微四个级别。「建议」通常用于优先级分类，不属于严重程度。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "以下哪个不是测试环境的常见层级？",
        "option_a": "开发环境（DEV）",
        "option_b": "测试环境（QA）",
        "option_c": "设计环境（DESIGN）",
        "option_d": "预发布环境（STAGING）",
        "correct_answer": "C",
        "explanation": "常见的环境层级包括开发环境、测试环境、预发布环境和生产环境。「设计环境」不属于标准的测试环境层级。",
        "difficulty": "easy",
    },
    {
        "question_type": "true_false",
        "title": "测试执行完成后就不需要再进行回归测试了。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "B",
        "explanation": "缺陷修复后需要进行回归测试，确保修复有效且未引入新的缺陷。回归测试是测试流程中不可缺少的环节。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "需求的可测试性不包括以下哪项？",
        "option_a": "明确性",
        "option_b": "可衡量性",
        "option_c": "可实现性",
        "option_d": "可变性",
        "correct_answer": "D",
        "explanation": "好的需求应满足明确性、可衡量性、可实现性和完整性。「可变性」不是需求可测试性的要求，反而频繁变更的需求不利于测试。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "测试总结报告通常不包括以下哪项内容？",
        "option_a": "测试执行情况",
        "option_b": "缺陷统计",
        "option_c": "源代码实现细节",
        "option_d": "改进建议",
        "correct_answer": "C",
        "explanation": "测试总结报告包括测试执行情况、缺陷统计、质量评估和改进建议，不包括源代码实现细节。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "以下哪种测试数据准备方法使用 Faker 等库自动生成数据？",
        "option_a": "手工创建",
        "option_b": "脚本生成",
        "option_c": "生产数据脱敏",
        "option_d": "数据工厂",
        "correct_answer": "D",
        "explanation": "数据工厂使用 Faker 等库自动生成模拟数据，可以快速创建大量测试数据。手工创建适合小规模数据，脚本生成是通用说法。",
        "difficulty": "medium",
    },
    {
        "question_type": "true_false",
        "title": "测试用例的基本要素包括用例编号、标题、前置条件、测试步骤和预期结果。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "A",
        "explanation": "测试用例的基本要素包括用例编号、用例标题、前置条件、测试步骤、预期结果、实际结果和执行状态。",
        "difficulty": "easy",
    },
    # ================================================================
    # 3. 测试用例设计方法 (7 题)
    # ================================================================
    {
        "question_type": "single",
        "title": "某输入框要求输入1-100的整数，使用边界值分析法，以下哪个测试值最可能发现缺陷？",
        "option_a": "50",
        "option_b": "0",
        "option_c": "100",
        "option_d": "200",
        "correct_answer": "B",
        "explanation": "边界值分析法关注边界附近的值。0是下界(1)的离点，最可能发现差一错误(off-by-one)。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "等价类划分法中，将输入数据分为有效等价类和什么？",
        "option_a": "边界等价类",
        "option_b": "无效等价类",
        "option_c": "特殊等价类",
        "option_d": "随机等价类",
        "correct_answer": "B",
        "explanation": "等价类划分将输入数据分为有效等价类（符合需求的合理输入）和无效等价类（不符合需求的不合理输入）。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "判定表适用于以下哪种情况？",
        "option_a": "单个条件的测试",
        "option_b": "多个条件组合的测试",
        "option_c": "界面美观度测试",
        "option_d": "性能测试",
        "correct_answer": "B",
        "explanation": "判定表用于描述多个条件组合与对应动作之间的关系，适合处理复杂的逻辑判断。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "以下哪项是白盒测试的覆盖标准？",
        "option_a": "等价类划分",
        "option_b": "边界值分析",
        "option_c": "路径覆盖",
        "option_d": "判定表",
        "correct_answer": "C",
        "explanation": "路径覆盖是白盒测试的覆盖标准。等价类划分、边界值分析和判定表都是黑盒测试方法。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "白盒测试中，以下哪种覆盖标准最强？",
        "option_a": "语句覆盖",
        "option_b": "判定覆盖",
        "option_c": "条件覆盖",
        "option_d": "路径覆盖",
        "correct_answer": "D",
        "explanation": "路径覆盖覆盖所有可能的执行路径，是白盒测试中覆盖标准最强的方法。覆盖强度：路径覆盖 > 条件覆盖 > 判定覆盖 > 语句覆盖。",
        "difficulty": "medium",
    },
    {
        "question_type": "true_false",
        "title": "白盒测试又称为结构测试，主要关注程序的内部逻辑结构。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "A",
        "explanation": "白盒测试确实又称为结构测试或逻辑驱动测试，它关注程序的内部结构和代码逻辑。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "状态转换测试中，以下哪项不是核心概念？",
        "option_a": "状态",
        "option_b": "事件",
        "option_c": "数据库表",
        "option_d": "转换",
        "correct_answer": "C",
        "explanation": "状态转换测试的核心概念包括状态、事件、转换和动作。「数据库表」不属于状态转换测试的核心概念。",
        "difficulty": "easy",
    },
    # ================================================================
    # 4. HTTP 与接口测试基础 (7 题)
    # ================================================================
    {
        "question_type": "single",
        "title": "HTTP方法中，用于获取资源的是？",
        "option_a": "POST",
        "option_b": "GET",
        "option_c": "PUT",
        "option_d": "DELETE",
        "correct_answer": "B",
        "explanation": "GET方法用于获取资源，参数在URL中。POST用于提交数据，PUT用于更新资源，DELETE用于删除资源。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "以下哪个HTTP方法用于提交数据，参数在请求体中？",
        "option_a": "GET",
        "option_b": "HEAD",
        "option_c": "POST",
        "option_d": "OPTIONS",
        "correct_answer": "C",
        "explanation": "POST方法用于提交数据，参数放在请求体中。GET方法的参数在URL中，HEAD只获取响应头，OPTIONS用于查询支持的方法。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "PUT和PATCH的主要区别是什么？",
        "option_a": "没有区别",
        "option_b": "PUT是全量替换，PATCH是部分更新",
        "option_c": "PUT用于创建，PATCH用于删除",
        "option_d": "PUT比PATCH更安全",
        "correct_answer": "B",
        "explanation": "PUT用于全量替换资源，PATCH用于部分更新资源。这是两者最主要的区别。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "HTTP状态码404表示什么？",
        "option_a": "服务器内部错误",
        "option_b": "请求成功",
        "option_c": "资源未找到",
        "option_d": "未授权",
        "correct_answer": "C",
        "explanation": "404 Not Found表示请求的资源不存在。200表示成功，500表示服务器内部错误，401表示未授权。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "HTTP状态码201 Created通常出现在什么操作之后？",
        "option_a": "GET请求",
        "option_b": "DELETE请求",
        "option_c": "成功创建资源的POST请求",
        "option_d": "页面重定向",
        "correct_answer": "C",
        "explanation": "201 Created表示资源创建成功，通常在POST请求成功创建新资源后返回。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "以下哪个状态码表示客户端请求参数错误？",
        "option_a": "400 Bad Request",
        "option_b": "401 Unauthorized",
        "option_c": "403 Forbidden",
        "option_d": "500 Internal Server Error",
        "correct_answer": "A",
        "explanation": "400 Bad Request表示请求参数有误。401表示未认证，403表示无权限，500表示服务器内部错误。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "以下哪个请求头用于指定请求体的数据格式？",
        "option_a": "Accept",
        "option_b": "Content-Type",
        "option_c": "Authorization",
        "option_d": "User-Agent",
        "correct_answer": "B",
        "explanation": "Content-Type 用于指定请求体的数据格式，如 application/json。Accept 指定期望的响应格式，Authorization 携带认证信息。",
        "difficulty": "medium",
    },
    # ================================================================
    # 5. 接口断言与验证 (6 题)
    # ================================================================
    {
        "question_type": "true_false",
        "title": "接口测试比UI测试执行速度更快，维护成本更低。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "A",
        "explanation": "接口测试不涉及UI渲染，执行速度更快，且接口相对稳定，维护成本低于UI测试。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "以下哪个不是常用的接口测试工具？",
        "option_a": "Postman",
        "option_b": "cURL",
        "option_c": "Photoshop",
        "option_d": "Python requests",
        "correct_answer": "C",
        "explanation": "Photoshop是图像处理软件，不是接口测试工具。Postman、cURL、Python requests都是常用的接口测试工具。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "在接口测试中，以下哪种断言用于验证HTTP响应状态码？",
        "option_a": "响应体断言",
        "option_b": "状态码断言",
        "option_c": "响应时间断言",
        "option_d": "响应头断言",
        "correct_answer": "B",
        "explanation": "状态码断言用于验证HTTP状态码是否符合预期，如200、404等。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "使用Python requests库进行接口断言，以下代码的断言验证了什么？\nassert resp.json()['code'] == 0",
        "option_a": "验证状态码为0",
        "option_b": "验证响应体JSON中code字段的值为0",
        "option_c": "验证响应时间为0",
        "option_d": "验证响应头中code为0",
        "correct_answer": "B",
        "explanation": "resp.json()解析响应体为JSON对象，['code']获取code字段，断言其值等于0。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "以下哪种断言用于验证接口响应时间？",
        "option_a": "状态码断言",
        "option_b": "字段值断言",
        "option_c": "响应时间断言",
        "option_d": "响应头断言",
        "correct_answer": "C",
        "explanation": "响应时间断言用于验证接口的响应时间是否在可接受范围内，如 < 2秒。",
        "difficulty": "easy",
    },
    {
        "question_type": "true_false",
        "title": "每个测试用例至少应包含一个断言。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "A",
        "explanation": "没有断言的测试用例无法验证结果，不能算作有效的测试。每个测试用例至少应包含一个断言。",
        "difficulty": "easy",
    },
    # ================================================================
    # 6. 自动化测试实践 (6 题)
    # ================================================================
    {
        "question_type": "single",
        "title": "以下哪种情况最适合进行自动化测试？",
        "option_a": "需求频繁变化的功能",
        "option_b": "一次性测试",
        "option_c": "回归测试",
        "option_d": "探索性测试",
        "correct_answer": "C",
        "explanation": "回归测试需要反复执行相同的测试用例，最适合自动化。需求频繁变化、一次性测试、探索性测试不适合自动化。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "pytest框架中，用于管理测试前准备和测试后清理的机制是什么？",
        "option_a": "装饰器",
        "option_b": "fixture",
        "option_c": "断言",
        "option_d": "参数化",
        "correct_answer": "B",
        "explanation": "fixture是pytest的核心机制，用于管理测试前的准备工作（setup）和测试后的清理工作（teardown）。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "以下哪项不是自动化测试的优势？",
        "option_a": "提高测试效率",
        "option_b": "支持回归测试",
        "option_c": "完全替代手工测试",
        "option_d": "减少人为错误",
        "correct_answer": "C",
        "explanation": "自动化测试不能完全替代手工测试，如探索性测试、用户体验测试等仍需手工完成。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "以下哪项是pytest的特点？",
        "option_a": "必须继承TestCase类",
        "option_b": "使用assert语句进行断言",
        "option_c": "必须使用setUp和tearDown",
        "option_d": "只支持单元测试",
        "correct_answer": "B",
        "explanation": "pytest使用原生的assert语句进行断言，无需继承TestCase类，也不强制使用setUp/tearDown。它支持多种类型的测试。",
        "difficulty": "easy",
    },
    {
        "question_type": "true_false",
        "title": "CI/CD 流水线中通常会集成自动化测试。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "A",
        "explanation": "持续集成/持续交付（CI/CD）流水线中集成自动化测试，可以在每次代码提交后自动运行测试，及时发现问题。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "接口自动化测试的第一步是什么？",
        "option_a": "编写测试脚本",
        "option_b": "执行测试",
        "option_c": "分析接口文档，确定测试范围",
        "option_d": "搭建测试环境",
        "correct_answer": "C",
        "explanation": "接口自动化测试的第一步是分析接口文档，了解接口的功能、参数和预期响应，然后确定测试范围。",
        "difficulty": "easy",
    },
    # ================================================================
    # 7. 缺陷管理与测试报告 (6 题)
    # ================================================================
    {
        "question_type": "single",
        "title": "缺陷生命周期中，「已修复」状态之后通常是什么？",
        "option_a": "关闭",
        "option_b": "新建",
        "option_c": "验证",
        "option_d": "重新打开",
        "correct_answer": "C",
        "explanation": "缺陷修复后进入「已修复」状态，接下来由测试人员进行验证。验证通过后关闭，验证不通过则重新打开。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "以下哪项不是缺陷报告的必要要素？",
        "option_a": "重现步骤",
        "option_b": "预期结果",
        "option_c": "修复方案",
        "option_d": "实际结果",
        "correct_answer": "C",
        "explanation": "缺陷报告应包含重现步骤、预期结果、实际结果等信息。「修复方案」由开发人员制定，不属于缺陷报告的必要要素。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "缺陷密度的计算公式是什么？",
        "option_a": "缺陷数 / 测试用例数",
        "option_b": "缺陷数 / 代码规模（千行）",
        "option_c": "修复缺陷数 / 总缺陷数",
        "option_d": "通过用例数 / 总用例数",
        "correct_answer": "B",
        "explanation": "缺陷密度 = 缺陷数 / 代码规模（千行），用于衡量代码质量。选项C是缺陷修复率，选项D是用例通过率。",
        "difficulty": "medium",
    },
    {
        "question_type": "true_false",
        "title": "缺陷的严重程度和优先级是同一个概念。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "B",
        "explanation": "严重程度描述缺陷对系统的影响程度，优先级描述修复缺陷的紧急程度。一个严重程度高的缺陷优先级不一定高（如边缘场景）。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "用例通过率的计算公式是什么？",
        "option_a": "已执行用例数 / 总用例数 × 100%",
        "option_b": "通过用例数 / 已执行用例数 × 100%",
        "option_c": "通过用例数 / 总用例数 × 100%",
        "option_d": "失败用例数 / 总用例数 × 100%",
        "correct_answer": "B",
        "explanation": "用例通过率 = 通过用例数 / 已执行用例数 × 100%。选项A是用例执行率。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "一个好的缺陷标题应该包含什么？",
        "option_a": "详细的代码分析",
        "option_b": "什么 + 在哪里 + 怎么了",
        "option_c": "完整的系统日志",
        "option_d": "开发人员的姓名",
        "correct_answer": "B",
        "explanation": "好的缺陷标题应简洁描述问题，包含「什么模块」+「在哪里」+「出了什么问题」三个要素。",
        "difficulty": "easy",
    },
    # ================================================================
    # 8. 性能测试基础 (5 题)
    # ================================================================
    {
        "question_type": "single",
        "title": "以下哪种性能测试用于观察系统在极限负载下的行为？",
        "option_a": "负载测试",
        "option_b": "压力测试",
        "option_c": "稳定性测试",
        "option_d": "基准测试",
        "correct_answer": "B",
        "explanation": "压力测试（Stress Testing）是超过系统承受能力的测试，用于观察系统的极限和容错能力。负载测试是在预期负载下的测试。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "以下哪项不是性能测试的关键指标？",
        "option_a": "响应时间",
        "option_b": "吞吐量",
        "option_c": "代码行数",
        "option_d": "错误率",
        "correct_answer": "C",
        "explanation": "性能测试的关键指标包括响应时间、吞吐量、并发用户数、错误率和资源利用率。「代码行数」不是性能指标。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "TPS 代表什么？",
        "option_a": "每秒事务数",
        "option_b": "每秒测试数",
        "option_c": "总处理速度",
        "option_d": "线程处理系统",
        "correct_answer": "A",
        "explanation": "TPS（Transactions Per Second）即每秒事务数，是衡量系统吞吐量的重要指标。",
        "difficulty": "easy",
    },
    {
        "question_type": "true_false",
        "title": "稳定性测试通常需要持续运行较长时间来检测内存泄漏等问题。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "A",
        "explanation": "稳定性测试（Endurance Testing）在目标负载下持续运行数小时甚至数天，用于检测内存泄漏、资源耗尽等长期运行问题。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "以下哪个是 Python 编写的负载测试工具？",
        "option_a": "JMeter",
        "option_b": "Locust",
        "option_c": "Gatling",
        "option_d": "wrk",
        "correct_answer": "B",
        "explanation": "Locust 是 Python 编写的开源负载测试工具，使用代码定义用户行为。JMeter 基于 Java，Gatling 基于 Scala，wrk 基于 C。",
        "difficulty": "medium",
    },
    # ================================================================
    # 9. 安全测试入门 (5 题)
    # ================================================================
    {
        "question_type": "single",
        "title": "以下哪种攻击通过在输入中注入恶意SQL语句来操纵数据库？",
        "option_a": "XSS",
        "option_b": "CSRF",
        "option_c": "SQL注入",
        "option_d": "DDoS",
        "correct_answer": "C",
        "explanation": "SQL注入是通过在输入中插入恶意SQL语句来操纵数据库的攻击方式。XSS是跨站脚本，CSRF是跨站请求伪造，DDoS是分布式拒绝服务。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "OWASP Top 10 主要关注什么？",
        "option_a": "性能测试标准",
        "option_b": "最严重的 Web 安全风险",
        "option_c": "自动化测试框架",
        "option_d": "代码质量规范",
        "correct_answer": "B",
        "explanation": "OWASP Top 10 是开放式 Web 应用安全项目发布的最严重的 Web 安全风险清单，是安全测试的重要参考。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "以下哪种攻击通过在页面中注入恶意脚本来窃取用户信息？",
        "option_a": "SQL注入",
        "option_b": "XSS（跨站脚本）",
        "option_c": "CSRF",
        "option_d": "DDoS",
        "correct_answer": "B",
        "explanation": "XSS（跨站脚本攻击）通过在网页中注入恶意脚本，当其他用户访问该页面时执行脚本，从而窃取 Cookie 等敏感信息。",
        "difficulty": "easy",
    },
    {
        "question_type": "single",
        "title": "以下哪项属于渗透测试的步骤？",
        "option_a": "编写用户手册",
        "option_b": "信息收集",
        "option_c": "功能验收",
        "option_d": "性能调优",
        "correct_answer": "B",
        "explanation": "渗透测试的步骤包括信息收集、漏洞发现、漏洞验证、报告编写和修复验证。信息收集是第一步。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "以下哪种措施可以有效防止 SQL 注入？",
        "option_a": "使用 HTTPS",
        "option_b": "参数化查询",
        "option_c": "增加服务器内存",
        "option_d": "使用 CDN",
        "correct_answer": "B",
        "explanation": "参数化查询（预编译语句）可以有效防止 SQL 注入，因为它将 SQL 语句和数据分开处理，不会将用户输入直接拼接到 SQL 中。",
        "difficulty": "medium",
    },
    {
        "question_type": "true_false",
        "title": "CSRF 攻击是利用用户已登录的身份，伪造请求执行非授权操作。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "correct_answer": "A",
        "explanation": "CSRF（跨站请求伪造）攻击利用用户已登录的身份，诱导用户点击恶意链接或访问恶意页面，从而伪造请求执行非授权操作。",
        "difficulty": "medium",
    },
    {
        "question_type": "single",
        "title": "以下哪个工具主要用于 Web 安全渗透测试？",
        "option_a": "pytest",
        "option_b": "JMeter",
        "option_c": "Burp Suite",
        "option_d": "Postman",
        "correct_answer": "C",
        "explanation": "Burp Suite 是 Web 安全测试的集成平台，用于渗透测试和漏洞扫描。pytest 是测试框架，JMeter 是性能工具，Postman 是接口测试工具。",
        "difficulty": "easy",
    },
]


def seed():
    """Insert questions. Skips any question whose title already exists."""
    with app.app_context():
        existing_titles = {
            q.title for q in db.session.query(Question.title).all()
        }
        inserted = 0
        for q_data in QUESTIONS:
            if q_data["title"] in existing_titles:
                continue
            question = Question(**q_data)
            db.session.add(question)
            existing_titles.add(q_data["title"])
            inserted += 1

        db.session.commit()
        if inserted:
            print(f"已插入 {inserted} 道题目。")
        else:
            print("所有题目数据已存在，跳过插入。")


if __name__ == "__main__":
    seed()
